#!/usr/bin/env node
// Generates adapters/atlas/util/version.ts from package.json#version.
// Runs as a prebuild step so the version is inlined into both `tsc` and
// `bun build --compile` outputs without runtime fs reads.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const pkgPath = resolve(repoRoot, 'package.json');
const outPath = resolve(repoRoot, 'adapters/atlas/util/version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version;
if (typeof version !== 'string' || version.length === 0) {
  console.error('[sync-version] package.json#version is missing');
  process.exit(1);
}

const banner = '// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.\n';
const body = `export const ATLAS_VERSION = ${JSON.stringify(version)};\n`;
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, banner + body);
console.log(`[sync-version] wrote ${outPath} = ${version}`);
